gbans_example.yml
internal/app/discord_commands.go
internal/app/discord_handlers.go

Since having reason as `nil` made Discord complain when /check was used
due to it not accepting an empty string as an embed message parameter,
this also adds a check for blank reasons for previous mutes and bans
made without a specified reason.

Add reason to mutes (second attempt)

---

sourcemod/scripting/gbans/globals.sp
sourcemod/scripting/gbans/stopwatch.sp

fixes the Stopwatch mode. tested on pl_upward, pl_swiftwater_final, pl_summercoast_rc8e, cp_sunshine, and cp_process_final with results as expected in each.
there is probably a better fix that can replace gb_stopwatch_changelevel_time involving using sm_mapvote_voteduration from nativevotes_mapchooser.sp to ensure the mapvote finishes, 35 should work on the Uncletopia config where this is most likely to be used.

fix stopwatch

---

frontend/src/api/server.ts
frontend/src/component/ServerList.tsx
internal/app/http_api.go
internal/app/state.go

Recent steam client removes the ability to use fqdn for protocol handlers `steam://connect/`.
This allows the use of either form in the backend, but automatically resolves the dns name for when used in a protocol handler link.

Use ip for steam:// protocol handler

---

internal/app/http_api.go

One api was changed when it shouldn't have been since it used query args and not a body

Fix bind call regression

---

frontend/src/api/bans.ts
frontend/src/component/BanASNModal.tsx
frontend/src/component/BanCIDRModal.tsx
frontend/src/component/BanGroupModal.tsx
frontend/src/component/BanSteamModal.tsx
frontend/src/component/formik/ASNumberField.tsx
frontend/src/component/formik/BanReasonTextField.tsx
frontend/src/component/formik/BanTypeField.tsx
frontend/src/component/formik/BaseFormikInputProps.tsx
frontend/src/component/formik/DurationCustomField.tsx
frontend/src/component/formik/GroupIdField.tsx
frontend/src/component/formik/IncludeFriendsField.tsx
frontend/src/component/formik/ReportIdField.tsx
frontend/src/page/AdminBan.tsx
internal/app/app.go
internal/app/app_background.go
internal/app/app_discord.go
internal/app/config.go
internal/app/http_api.go
internal/store/ban.go
internal/store/migrations/000070_add_members_table.down.sql
internal/store/migrations/000070_add_members_table.up.sql
internal/store/store_test.go

Some of this functionaly already existed, however this moves it into the database instead of the static config file.
- Enables the group ban feature in UI
- Adds a `include_friends` field to mark players who friend list will also get dropped. When the parent ban is expired
- Save archive of banned players to reference incase of private profile/group changes

Improve Group Bans & Add Deep Steam Bans

---

sourcemod/scripting/gbans.sp
sourcemod/scripting/gbans/balance.sp
sourcemod/scripting/gbans/globals.sp

Disabled users from using autoteam command to swap to full teams

Disable Autoteam

---

frontend/src/component/ReportViewComponent.tsx
frontend/src/component/formik/DemoTickField.tsx
internal/app/app.go
internal/app/app_background.go
internal/app/config.go
internal/app/http_api_server.go
internal/app/s3.go
internal/store/demo.go

- Fix report demo using old download link
- Update demo cleanup func to remove from S3 as well as limit demo to N rows
- Add demo_cleanup_enabled and demo_count_limit for configuring demo cleanups

Demo Download & Report Fixes

---

frontend/src/api/bans.ts
frontend/src/api/common.ts
frontend/src/api/report.ts
frontend/src/component/modal/BanSteamModal.tsx
frontend/src/routes/_auth.report.index.tsx
frontend/src/routes/_guest.stv.tsx
frontend/src/routes/_mod.admin.appeals.tsx
frontend/src/routes/_mod.admin.reports.tsx
frontend/src/util/table.ts
internal/appeal/appeal_repository.go
internal/appeal/appeal_service.go
internal/appeal/appeal_usecase.go
internal/ban/ban_steam_usecase.go
internal/discord/discord_service.go
internal/discord/responses.go
internal/domain/appeal.go
internal/domain/query_filter.go
internal/domain/report.go
internal/report/report_repository.go
internal/report/report_service.go
internal/report/report_usecase.go

- Fixes default ordering
- Migrate to client side data filtering
- Add error flash for duplicate ban
- Fix discord unban command output error

Appeal/Report/Ban Table Bug fixes

---

frontend/src/routes/_guest.stv.tsx

The STV filters currently do not apply the steamid filter without having to submit the form twice. It also happens on initial page load if the steamid is provided int he urlsearch params.
Not sure why only this particularly field behaves t his way. This very hacky workaround just double submits the form for now.

(Bad) Worfaround around for STV filtering & double submit

---

frontend/src/component/Title.tsx
frontend/src/routes/_guest.servers.tsx

First try at #482 
Incredibly, tanstack router doesn't seem to have a standard solution for page titles: https://github.com/TanStack/router/discussions/1056
That said, I would expect them to eventually follow React's API lead: https://react.dev/reference/react-dom/components/title#set-the-document-title so I made a very simple `<Title>` component which should be easy to swap out to `<title>` in the future.
As far I saw this app has no SSR, so I just directly mutate document.title.
Would you prefer the title always end in `| ${site_name}`? We can likely inject that from the vite config.

Add <Title> component and first usage on /servers

---

frontend/index.html
frontend/src/api/media.ts
frontend/src/component/Footer.tsx
frontend/src/component/MarkdownRenderer.tsx
frontend/src/component/Title.tsx
frontend/src/component/TopBar.tsx
frontend/src/index.tsx
frontend/src/routes/_auth.forums.index.tsx
frontend/src/routes/_guest.index.tsx
frontend/src/routes/_guest.privacy-policy.tsx
frontend/src/routes/_guest.servers.tsx
frontend/src/vite-env.d.ts
frontend/vite.config.ts

I did this refactor for https://github.com/leighmacdonald/gbans/pull/503 before realizing I could just use `window.gbans.site_name`
Figured I'd offer this to you anyways as using Vite defines is a bit more idiomatic and compiles a little more efficiently (it saves ~200 bytes off of index.html and ~1kb off of index.js)
I tested by poking around the site and also running `./node_modules/.bin/tsc --noEmit` and noticing no new type errors. release.sh also still works.
This PR temporarily is stacked on top of the commit from https://github.com/leighmacdonald/gbans/pull/503... sorry, I'm not sure about modern github etiquette for stacked commits, I'll sort it out as that PR lands.

Switch frontend globals to use Vite defines

---

frontend/src/component/modal/ServerEditorModal.tsx
frontend/src/routes/_admin.admin.servers.tsx
internal/servers/servers_service.go

this fixes the server auth key from not being saved in the server creator/editor. also hopefully makes it clearer that it is an auth key not the password to join the server. better solution would be to have the key be randomly generated.

fix server auth key not saving

---

internal/discord/discord_repository.go

Even with discord "disabled" in gbans.yml, trying to run gbans fails with: `Failed to start discord error=websocket: close 4004: Authentication failed.\nfailed to open discord connection`.
I avoided this with the Null Object Pattern.

Fix running server with Discord disabled

---

frontend/src/api/bans.ts
internal/chat/chat_repository.go
internal/chat/chat_usecase.go
internal/domain/chat.go
internal/domain/model.go
internal/domain/person.go
internal/domain/state.go
internal/state/state_usecase.go
internal/wordfilter/wordfilter_repository.go

Rather than adding much specialized handling I just treat a connect event as a chat message with the player's name in it. This is a bit annoying since it shows up on the site's chat log, but I suppose it could be a good log to protect against users changing their names a lot (in an attempt to hide something offensive). Followups could hide those messages from showing up on the site.
While testing on my server, I realized that automatic actions on chat messages didn't seem to be working at all (maybe I'm missing some setup?). I fixed that here by having chat_usecase listen to chat_repository's WarningChan.
Another new change here is that we kick based off of the server id and player id from the log event instead of doing a lookup by steamid. This is pretty necessary as it's very unlikely …

Apply word filtering rules to usernames on player connect

---

frontend/src/api/profile.ts
frontend/src/routes/_auth.settings.tsx
internal/cmd/net.go
internal/cmd/refresh.go
internal/cmd/serve.go
internal/cmd/setup.go
internal/database/migrations/000095_add_centerprojectiles.down.sql
internal/database/migrations/000095_add_centerprojectiles.up.sql
internal/domain/config.go
internal/domain/person.go
internal/person/person_repository.go
internal/person/person_usecase.go

Part of #373 
Allows configuring tf2centerprojectiles from the user settings page.
The visual UI changes and new DB queries are both gated behind a new config flag, as this requires some annoying sourcemod setup... we may need some amendments to this if you are segmenting your sourcemod tables in a different db schema.
The queries are a bit icky but are intended to be easy to add support for more clientprefs down the line (ie #520)
Tested: with the new config flag disabled, the settings page looks the same as on master. With the new config flag, there is a new accordion+checkbox which reads/updates the sm_cookie_cache table correctly. Updating the setting then joining a server results in the client getting the new setting.
----
Clientprefs sql init does create an SQL function [for …

Allow configuring center_projectiles clientpref from site settings

---

internal/demo/demo_respository.go
internal/demo/demo_usecase.go
internal/domain/demo.go

Changes how archived status is determined by comparing for a matching value in report table.

Fix expired demos query archive status

---

internal/config/config_usecase.go
internal/config/helper.go
internal/discord/discord_repository.go
internal/discord/discord_service.go
internal/discord/responses.go
internal/domain/discord.go
internal/domain/errors.go
internal/domain/state.go
internal/state/collector.go

Removes the no longer necessary and bad /set_steam command. Users will need to connect their accounts under their settings instead.
closes #560

Drop /set_steam

---

internal/asset/asset_repository_local.go
internal/asset/asset_usecase.go
internal/demo/demo_respository.go
internal/demo/demo_usecase.go
internal/demo/fetcher.go
internal/domain/asset.go
internal/domain/demo.go
internal/test/demos_test.go
internal/test/main_test.go

- Add a check to cleanup orphaned demos (demos which do not exist on disk anymore despite a database entry)
- Add explicit call to delete demo since the FK cascade does not seem to function correctly. Issue still TBD, but this works as a temp fix.
- Fix query for querying expired demos.

Cleanup orphaned demos

---

internal/demo/fetcher.go

Fixes ssh execer not using the configurable interval value.

Use Config.SSH.UpdateInterval value

---

frontend/src/api/server.ts
frontend/src/component/modal/ServerEditorModal.tsx
internal/cmd/serve.go
internal/database/migrations/000104_add_address_internal.down.sql
internal/database/migrations/000104_add_address_internal.up.sql
internal/demo/fetcher.go
internal/domain/server.go
internal/network/scp.go
internal/servers/servers_repository.go
internal/servers/servers_usecase.go
internal/state/collector.go
internal/state/state_usecase.go

Addes a address_internal field to server struct/db. When not empty, will be used in place of the standard address. This is designed for cases where ssh, and potentially over services in the future, is only exposed over the internal/vpn interface.

Add support for internal address

---

frontend/src/api/playerqueue.ts

This currently forms an invalid url that starts with `wss:://`

Fix websockets connection on https site

---

internal/domain/server.go
internal/state/state_usecase.go
pkg/logparse/udp_listener.go

Manually tested that `nc -u 0.0.0.0 27715` fails from an IP that is not listed on any servers and chat message logging still works from an IP that is associated with a server.
While it's a security improvement, this is a breaking change, so I can add a setting for it if you'd like.

Validate server addresses for UDP log messages. Fixes #605
