leighmacdonald/gbans

.github/workflows/release.yml, .gitignore, frontend/src/App.tsx, frontend/src/component/PrivateRoute.tsx, frontend/src/component/TopBar.tsx, frontend/src/page/LoginSuccess.tsx, frontend/src/util/api.ts, internal/model/model.go, internal/model/permission.go, internal/service/auth.go, internal/service/db.go, internal/service/http_api.go, internal/service/http_api_test.go, internal/service/routes.go, migrations/000011_add_permission_level.down.sql, migrations/000011_add_permission_level.up.sql
Very simple as i think the apps purpose doesn't really dictate the need for anything else at this point in time.
`person.permission_level ` defines the users level.
Current levels are as follows:
```go
type Privilege uint8
const (
PGuest         Privilege = 1
PBanned        Privilege = 2 // Logged in, but is banned
PAuthenticated Privilege = 10
PModerator     Privilege = 50
PAdmin         Privilege = 100
)
```
=> Basic authentication mechanism implemented

internal/external/logstf.go, internal/external/logstf_test.go, internal/model/model.go, internal/service/bot.go, internal/service/bot_commands.go, internal/service/bot_handlers.go, internal/service/db.go, migrations/000012_add_discord_id.down.sql, migrations/000012_add_discord_id.up.sql
/check will now show discord user who banned
=> Enable linking discord and steam accounts

internal/config/config.go, internal/service/actions.go, internal/service/auth.go, internal/service/bot_handlers.go, internal/service/steam_api.go
Adds
```
┌──────────────────────────────────────────────────────────────────────────────────────────────┐
│ Profile of: camp3r                                                                           │
├───────────┬─────────────────────────────┬─────────┬──────────────────────────────────────────┤
│ Real Name │                             │ Profile │ https://steamcommunity.com/id/camp3r101/ │
│ SID64     │ 76561197992870439           │ SID     │ STEAM_0:1:16302355                       │
│ STEAM3    │ [U:1:32604710]              │ STEAM32 │ 32604711                                 │
│ Banned    │ true                        │ Muted   │ false                                    │
│ Reason    │ test                        │         │                                          │
│ Created   │ …
```
=> /check formatting improvements

internal/model/model.go, internal/service/app_test.go, internal/service/db.go, internal/service/db_test.go, internal/service/http_api.go, internal/service/http_api_test.go, internal/service/migrations/000013_log_player_ips.down.sql, internal/service/migrations/000013_log_player_ips.up.sql, internal/service/steam_api.go
Enables the historical recording of ip usage for players who connect.
=> Record player IPs on connection.

internal/cmd/net.go, internal/config/config.go, internal/service/bot.go, internal/service/bot_handlers.go, internal/service/db.go, internal/service/migrations/000014_create_block_tables.down.sql, internal/service/migrations/000014_create_block_tables.up.sql, pkg/ip2location/ip2location.go, pkg/util/conversion.go
Adds initial integration of ip2location datasets. 
Downloading, caches, import to pg, simple querying.
`gbans net update`
=> #41 Network blocks

docker/docker-compose-test.yml, internal/model/model.go, internal/model/model_test.go, internal/service/app.go, internal/service/app_test.go, internal/service/bot_commands.go, internal/service/bot_handlers.go, internal/service/db.go, internal/service/db_test.go, internal/service/http_api.go, pkg/util/text.go, pkg/util/text_test.go
Implements basic filters. No actions currently take place upon a match.
=> Add initial implementation of configurable word filters #11

internal/action/action.go, internal/app/actions.go, internal/app/app.go, internal/app/background.go, internal/discord/bot.go, internal/discord/bot_commands.go, internal/discord/bot_handlers.go, internal/model/model.go, internal/store/db_net.go, internal/store/db_test.go, internal/store/migrations/000016_ip_index.down.sql, internal/store/migrations/000016_ip_index.up.sql, internal/store/migrations/000019_server_log_flatten.down.sql, internal/store/migrations/000026_add_ban_asn_table.down.sql, internal/store/migrations/000026_add_ban_asn_table.up.sql, internal/store/store.go, internal/web/http_api.go, pkg/ip2location/ip2location.go, pkg/util/network.go
Adds initial support for blocking specific ASNs.
`/ban asn asnum duration [reason]`
`/unban asn`
closes #41
=> ASN Block Support

docs/INSTALL.md, gbans_example.yml
This PR is largely just to deal with some basic frustrations a new user might face when trying to get Gbans running for the first time. 
A full changelist, since this isn't an *entirely* atomic PR:
- Example config is better commented, explaining what the fields are in a little more depth
- INSTALL.md is updated with some estimations of the hardware needed
- Added reverse proxy example for Apache, for anyone wanting to run Gbans alongside existing sites for density purposes
- Added instructions on how to load up the IP2Location data
- Added instructions on how to get player location working on the server list after the browser API was removed
- Updated the sample badwords list, as the user re-arranged the repository and changed their username
These have largely been figured out through …
=> Expanded documentation of config file and "getting started" process

.github/workflows/release.yml
- Upgrade goreleaser version to 5
- Set go-version to stable.
=> Update release actions

.github/workflows/release.yml
Use secrets.GITHUB_TOKEN instead of secrets.GH_PAT
=> Change to GITHUB_TOKEN 

.github/workflows/deploy.yml, .goreleaser.yaml, Dockerfile, README.md, docker/release.Dockerfile, docs/INSTALL.md, internal/app/app_background.go, internal/app/s3.go, internal/cmd/serve.go, internal/store/demo.go, internal/store/server.go, internal/store/stats.go
Fixes some issues encountered when deploying.
- Add more logging output.
- Don't error out on no servers
=> S3 Config Improvements

.goreleaser.yaml, frontend/src/component/Footer.tsx, frontend/src/index.tsx, internal/app/app.go, internal/app/http_api.go, internal/app/http_routes.go, internal/app/s3.go
- Fixes demo insertion due to missing asset id.
Also enables showing build info.
=> Fix Demo Asset ID

internal/app/http_api.go
Use the provided demo name instead of autogenerated uuid for file name
=> Use Demo Name

frontend/src/App.tsx, frontend/src/component/Footer.tsx, frontend/src/page/PrivacyPolicyPage.tsx, internal/app/http_routes.go, sourcemod/scripting/gbans/auth.sp
- Adds a privacy policy
- Link in footer
=> Add Privacy Policy

Dockerfile, Makefile, docs/INSTALL.md, frontend/package.json, internal/store/demo.go
Adds missing constraints to demo query
=> Fix missing demo query limits

internal/store/ban.go, internal/store/net.go, pkg/logparse/udp_listener.go
- Fix typo in column name
- Use pgtype.CIDR type
=> Fix Some Bans Not Expiring

frontend/src/api/server.ts, frontend/src/component/modal/ServerEditorModal.tsx, frontend/src/page/AdminServersPage.tsx, frontend/src/page/ChatLogPage.tsx, internal/app/app.go, internal/app/app_background.go, internal/app/http_api_admin.go, internal/app/http_api_server.go, internal/app/state.go, internal/store/migrations/000073_add_server_id_tracking.down.sql, internal/store/migrations/000073_add_server_id_tracking.up.sql, internal/store/person.go, internal/store/server.go
- Allow disabling of stats recording for specific server instances.
- Updates server config modal with log_secret and enable_stats fields.
=> Per Instance Stats Toggle

frontend/src/component/MarkdownRenderer.tsx, internal/store/ban.go
- Remove appeals which have not started yet
- Fix markdown renderer not using overrides
=> Minor fixes

frontend/src/App.tsx, frontend/src/component/Flashes.tsx, frontend/src/component/TopBar.tsx, frontend/src/component/formik/SteamIdField.tsx, frontend/src/component/modal/BanSteamModal.tsx, frontend/src/contexts/NotificationsCtx.tsx
Migrates notification popups to the Snackbar + Alert compnents
=> Use Toast Notification

internal/app/http_api_authed.go
Fixes report queries for admins
=> Fix report query source_id

frontend/src/api/forum.ts, frontend/src/api/profile.ts, frontend/src/component/Accordian.tsx, frontend/src/component/ContainerWithHeader.tsx, frontend/src/component/LoadingHeaderIcon.tsx, frontend/src/component/LoadingIcon.tsx, frontend/src/component/TopBar.tsx, frontend/src/component/formik/ForumProfileMessagesField.tsx, frontend/src/component/formik/StatsHiddenField.tsx, frontend/src/hooks/usePersonSettings.tsx, frontend/src/hooks/useProfile.ts, frontend/src/page/ForumThreadPage.tsx, frontend/src/page/ProfilePage.tsx, frontend/src/page/ProfileSettingsPage.tsx, internal/app/http_api.go, internal/app/http_api_authed.go, internal/app/http_routes.go, internal/store/forum.go, internal/store/migrations/000076_person_settings.down.sql, internal/store/migrations/000076_person_settings.up.sql, internal/store/person.go, sourcemod/scripting/gbans/auth.sp
- User settings page
- Forum signatures
- Stats on profile page respect users settings
=> Forum Signatures & User Settings

internal/app/app.go, internal/app/http_api_server.go, internal/store/ban.go, internal/store/migrations/000079_add_last_ip.down.sql, internal/store/migrations/000079_add_last_ip.up.sql, internal/store/net.go
Tracks last ip of banned players and bans subsequent players if they connect from the same ip with a different account.
=> Ban alts of previously banned players

frontend/src/page/WikiPage.tsx
Adds permission check for showing edit button in ui for non editors.
=> Fix edit button showing up for non editors.

frontend/src/api/bans.ts, frontend/src/api/server.ts, frontend/src/component/formik/DurationStringField.tsx, frontend/src/component/modal/BanSteamModal.tsx, frontend/src/component/modal/ServerEditorModal.tsx, frontend/src/component/table/BanASNTable.tsx, frontend/src/component/table/BanCIDRTable.tsx, frontend/src/component/table/BanGroupTable.tsx, frontend/src/component/table/BanSteamTable.tsx, frontend/src/page/AdminAppealsPage.tsx, frontend/src/page/AdminFiltersPage.tsx, frontend/src/page/AdminPeoplePage.tsx, frontend/src/page/AdminReportsPage.tsx, frontend/src/page/AdminServersPage.tsx, frontend/src/page/HomePage.tsx
Improve layout for smaller screen sized.
Additionally adds more url states to admin person/servers pages.
=> Mobile Layout Updates

frontend/src/api/stats.ts, frontend/src/component/HealersOverallContainer.tsx, frontend/src/component/PlayerWeaponsStatListContainer.tsx, frontend/src/component/PlayersOverallContainer.tsx, frontend/src/hooks/useHealerOverallStats.ts, frontend/src/hooks/usePlayerWeaponsOverallStats.ts, frontend/src/hooks/usePlayersOverallStats.ts, frontend/src/hooks/useWeaponsOverallStats.ts, frontend/src/hooks/useWeaponsStats.ts, frontend/src/page/ProfilePage.tsx, frontend/src/page/StatsPage.tsx, frontend/src/page/StatsWeaponOverallPage.tsx, internal/store/stats.go
- Fixup paging for stats tables
- Add hooks for stats
=> Fixup paging for stats tables

internal/app/app_background.go, internal/store/person.go
Increases the interval which a profile is considered out of date and also increases the update frequency of checking for new updates.
=> Increase profile update intervals

.github/workflows/test.yml, Makefile, frontend/src/api/profile.ts, frontend/src/component/modal/Buttons.tsx, frontend/src/component/table/ConnectionHistoryTable.tsx, frontend/src/component/table/connectionColumns.tsx, frontend/src/hooks/useConnectionsBySteamID.ts, frontend/src/page/AdminNetworkPage.tsx, internal/domain/net.go, internal/domain/query_filter.go, internal/network/network_repository.go, internal/network/network_service.go, internal/network/network_usecase.go
Adds ability to query all player IPs
=> Admin IP Query Form

frontend/src/App.tsx, frontend/src/api/profile.ts, frontend/src/api/votes.ts, frontend/src/component/TopBar.tsx, frontend/src/component/formik/DeletedField.tsx, frontend/src/component/formik/FilterButtons.tsx, frontend/src/hooks/useVotes.ts, frontend/src/page/AdminVotesPage.tsx, internal/chat/chat_repository.go, internal/cmd/refresh.go, internal/cmd/serve.go, internal/database/migrations/000083_vote_logs.down.sql, internal/database/migrations/000083_vote_logs.up.sql, internal/demo/demo_usecase.go, internal/discord/responses.go, internal/domain/chat.go, internal/domain/net.go, internal/domain/vote.go, internal/state/collector.go, internal/state/state_usecase.go, internal/votes/vote_repository.go, internal/votes/vote_service.go, internal/votes/vote_usecase.go, pkg/logparse/consts.go, pkg/logparse/event.go, pkg/logparse/log_parser.go, pkg/logparse/log_parser_test.go, pkg/logparse/udp_listener.go
- Adds support for logging user ingame votes.
- Includes a mod page for searching through the history
=> User Vote Logging And Querying

.gitignore, frontend/frontend.go, frontend/src/App.tsx, frontend/src/component/FindPlayerIPs.tsx, frontend/src/component/FindPlayesrByCIDR.tsx, frontend/src/component/NetworkInfo.tsx, frontend/src/component/TopBar.tsx, frontend/src/component/nested-menu/components/ContextMenu.tsx, frontend/src/component/nested-menu/components/IconMenuItem.tsx, frontend/src/component/nested-menu/components/NestedDropdown.tsx, frontend/src/component/nested-menu/components/NestedMenuItem.tsx, frontend/src/component/nested-menu/components/index.ts, frontend/src/component/nested-menu/components/nestedMenuItemsFromObject.tsx, frontend/src/component/nested-menu/definitions.ts, frontend/src/component/nested-menu/icons/ChevronDown.tsx, frontend/src/component/nested-menu/icons/ChevronRight.tsx, frontend/src/component/nested-menu/index.ts, frontend/src/page/AdminNetworkCIDRBlocksPage.tsx, frontend/src/page/AdminNetworkInfoPage.tsx, frontend/src/page/AdminNetworkPage.tsx, frontend/src/page/AdminNetworkPlayerIPHistoryPage.tsx, frontend/src/page/AdminNetworkPlayersByCIDRPage.tsx
- Splits network tools into distint pages
- Adds nested menu components to admin menu
- Use urlState for network tools
=> Network Page Split & New Sub Menu

frontend/src/api/bans.ts, frontend/src/component/TopBar.tsx, frontend/src/component/formik/EvadeOKField.tsx, frontend/src/component/modal/BanSteamModal.tsx, frontend/src/component/nested-menu/components/nestedMenuItemsFromObject.tsx, frontend/src/component/table/BanSteamTable.tsx, frontend/src/page/AdminVotesPage.tsx, internal/ban/ban_steam_repository.go, internal/ban/ban_steam_service.go, internal/ban/ban_steam_usecase.go, internal/chat/chat_usecase.go, internal/database/migrations/000084_ban_whitelist.down.sql, internal/database/migrations/000084_ban_whitelist.up.sql, internal/discord/discord_service.go, internal/domain/ban.go, internal/srcds/srcds_service.go
- Enables the ability to whitelist some ips from auto issueing perma bans for "evaders" (people connecting from the same ip as a currently banned player).
- Improve drop down menu layout / styling
=> Evader Whitelist Support

internal/ban/ban_steam_repository.go
Adds missing param column value
=> Fix ban insert query

frontend/index.html, frontend/vite.config.ts
Fixes injecting the site_name variable for the titles
=> Fix Site Name Injection

internal/ban/ban_steam_service.go, internal/config/helper.go, internal/domain/config.go
=> Restrict ban exports

frontend/src/api/server.ts, frontend/src/routes/_admin.admin.servers.lazy.tsx
=> Add Auth Time To Servers Table

frontend/.prettierignore, frontend/.prettierrc, frontend/src/routes/_guest.profile.$steamId.lazy.tsx
Also adds an ignore for formatting src/routeTree.gen.ts
closes #491
=> Fix Loading Incorrect Profiles For /profile

frontend/src/component/ProfileInfoBox.tsx, frontend/src/routes/_guest.profile.$steamId.tsx
Accidentally left some debug stuff that added doubled names. Removed.
closes #510
=> Fix Doubled Names

frontend/src/api/server.ts
=> Add Missing Date Transform

frontend/src/App.tsx, frontend/src/api/common.ts, frontend/src/auth.tsx, frontend/src/component/TopBar.tsx, frontend/src/routeTree.gen.ts, frontend/src/routes/_auth.ban.$ban_id.tsx, frontend/src/routes/_auth.report.index.tsx, frontend/src/routes/_guest.index.tsx, frontend/src/routes/_mod.admin.network.iphist.tsx, frontend/src/util/auth/guestProfile.ts, frontend/src/util/auth/logoutFn.ts, internal/auth/auth_service.go
Moves profile state into a useState outside of AuthContext
closes #518
closes #514
=> Fix Profile State Propogation

internal/network/scp.go
Hopefully fixes it, but mostly untested.
fixes #523
=> Add defer for scp client

frontend/src/component/modal/SteamWhitelistEditorModal.tsx, frontend/src/routes/_auth.ban.$ban_id.tsx, internal/appeal/appeal_usecase.go, internal/auth/auth_usecase.go, internal/ban/ban_steam_repository.go, internal/ban/ban_steam_service.go, internal/ban/ban_steam_usecase.go, internal/blocklist/blocklist_repository.go, internal/blocklist/blocklist_usecase.go, internal/cmd/serve.go, internal/database/migrations/000092_evade_skip.down.sql, internal/database/migrations/000092_evade_skip.up.sql, internal/demo/fetcher.go, internal/discord/discord_service.go, internal/domain/ban.go, internal/domain/blocklist.go, internal/domain/srcds.go, internal/srcds/srcds_repository.go, internal/srcds/srcds_service.go, internal/srcds/srcds_usecase.go, internal/state/state_usecase.go, sourcemod/scripting/gbans.sp, sourcemod/scripting/gbans/admins.sp, sourcemod/scripting/gbans/auth.sp, sourcemod/scripting/gbans/globals.sp, sourcemod/scripting/include/gbans.inc
- Improve logic for detecting evaders and how they are applied.
- Fixes support for whitelisted ips and steamids from cidr & network bans.
- Fix missing mapping value for loading sourcemod admin groups.
=> Improve Evade Handling

frontend/src/api/report.ts, frontend/src/routeTree.gen.ts, frontend/src/routes/_auth.report.index.tsx, internal/domain/report.go, internal/report/report_repository.go, internal/report/report_service.go, internal/report/report_usecase.go
Adds a secondary endpoint to retrieve only reports by the requester.
=> Add user specific reports endpoint

frontend/src/api/demo.ts, frontend/src/routes/_admin.admin.settings.tsx, frontend/src/theme.ts, go.mod, go.sum, internal/asset/asset_repository_local.go, internal/asset/asset_usecase.go, internal/demo/demo_respository.go, internal/demo/demo_service.go, internal/demo/demo_usecase.go, internal/demo/fetcher.go, internal/domain/asset.go, internal/domain/demo.go, internal/report/report_service.go
- Cleanup of demo strategy handler. 
- Prints total removed.
- More logging
=> Demo cleanup trigger and more logging.

frontend/src/api/bans.ts, frontend/src/component/ContainerWithHeader.tsx, frontend/src/component/field/MarkdownField.css, frontend/src/component/field/MarkdownField.tsx, frontend/src/component/modal/BanSteamModal.tsx, frontend/src/routes/_auth.report.$reportId.tsx, frontend/src/routes/_auth.report.index.tsx, internal/ban/ban_steam_service.go
- Fixes error loading state
- Expands on existing data to include more details
- Improve state logic
=> Improve Report Page Ban State

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/component/ChatTable.tsx, frontend/src/component/PlayerWeaponsStatListContainer.tsx, frontend/src/component/WeaponsStatListContainer.tsx, frontend/src/component/field/MarkdownField.tsx, frontend/src/routes/_auth.report.index.tsx, frontend/src/routes/_guest.stv.tsx, frontend/src/routes/_mod.admin.appeals.tsx, frontend/src/routes/_mod.admin.ban.steam.tsx, frontend/src/routes/_mod.admin.reports.tsx, frontend/src/util/colours.ts
Generate colours using HSL luminance with different sets for light/dark mode
=> Improve String To Colour

frontend/src/api/news.ts, frontend/src/component/modal/NewsEditModal.tsx, frontend/src/component/modal/index.ts, frontend/src/routes/_auth.settings.tsx, frontend/src/routes/_guest.stv.tsx, frontend/src/routes/_mod.admin.news.tsx, internal/news/news_service.go, internal/news/news_usecase.go, internal/srcds/srcds_repository.go
Migrate news to match ux of other admin areas.
closes #525
=> Update Mod News Page Layout

internal/ban/background.go, internal/ban/ban_asn_usecase.go, internal/ban/ban_steam_usecase.go, internal/cmd/refresh.go, internal/cmd/serve.go, internal/discord/discord_repository.go, internal/discord/discord_service.go, internal/discord/discord_usecase.go, internal/discord/responses.go, internal/domain/discord.go, internal/news/news_service.go, internal/person/person_service.go, internal/report/report_service.go, internal/votes/vote_usecase.go, internal/wordfilter/wordfilter_usecase.go
Updates the discord channel config to not default to the generic mod channel
=> Discord Channel ID Updates

.github/workflows/release.yml, .github/workflows/test.yml, .goreleaser.yaml, SECURITY.md
- Enables testing the building of the plugin
- Compile and include the plugin in the release workflow assets.
=> Sourcemod build workflow

internal/asset/asset_service.go
Fixes incorrect form validator being used on backend.
=> Fix image form uploads

frontend/src/api/admin.ts, frontend/src/routes/_admin.admin.settings.tsx, internal/ban/ban_steam_service.go, internal/config/config_repository.go, internal/domain/config.go, internal/test/config_test.go
- Fixes invalid validation type
- Adds a basic field for defining keys. Will be improved at a later date.
=> Fix exports settings validation

frontend/src/component/DesktopNotifications.tsx, frontend/src/component/TopBar.tsx, frontend/src/routes/_auth.settings.tsx
Adds support for enabling and showing desktop notifications for new messages.
=> Desktop Notifications

frontend/src/api/server.ts, frontend/src/component/QueueProvider.tsx, frontend/src/component/ServerList.tsx, frontend/src/component/TopBar.tsx, internal/domain/server.go, internal/domain/state.go, internal/servers/servers_service.go, internal/state/collector.go
Instead of summing the rows of players, parse the `players : ` header line for humans, bots, max players.
=> Change how players are counted

frontend/src/component/MarkdownRenderer.tsx, frontend/src/component/QueueChatMessageContainer.tsx, frontend/src/component/QueueProvider.tsx, frontend/src/routes/_auth.report.index.tsx, frontend/src/util/time.ts, internal/asset/asset_service.go
Fixes user image upload handler
=> Upload image fix

frontend/src/routes/_auth.notifications.tsx
Adds a media query to swap to `IconButton` from `Button` for smaller screens.
=> Improve Mobile Notifiaction Icons

frontend/src/component/modal/ServerEditorModal.tsx, frontend/src/schema/server.ts, internal/database/database.go, internal/database/migrate.go, internal/database/migrations/000108_add_sdr_config.down.sql, internal/database/migrations/000108_add_sdr_config.up.sql, internal/domain/server.go, internal/network/dns/dns.go, internal/servers/servers_repository.go, internal/servers/servers_usecase.go, internal/state/collector.go
- Adds better support for sdr servers configured with automatically updating DNS.
=> Improve SDR Server Support

.gitignore, frontend/src/routes/_admin.admin.settings.tsx, frontend/src/schema/config.ts
Adds the anticheat section under the admin settings page.
=> Add anticheat settings to ui.
